apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    # hooks are defined here
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi02ODExNjEiLAogICAgICAgICAgICAicGFzc3dvcmQiOiJzcWpITW51TWs2Y2V5N3kzOTJVUiIsCiAgICAgICAgICAgICJlbWFpbCI6ImZhbnRhc21hb3A3QGdtYWlsLmNvbSIsCiAgICAgICAgICAgICJhdXRoIjoiWjJsMGJHRmlLMlJsY0d4dmVTMTBiMnRsYmkwMk9ERXhOakU2YzNGcVNFMXVkVTFyTm1ObGVUZDVNemt5VlZJPSIKICAgIAl9CiAgICB9Cn0=