{{- if and .Values.tls.certData .Values.tls.keyData -}}
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-tls
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    helm.sh/chart: {{ include "backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  tls.crt: {{ .Values.tls.certData | b64enc }}
  tls.key: {{ .Values.tls.keyData | b64enc }}
  server.crt: {{ .Values.tls.certData | b64enc }}
  server.key: {{ .Values.tls.keyData | b64enc }}

{{- end -}}